version: "3"  # optional since v1.27.0
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432

  server:
    image: gregorymacat/service-products:app_1.0
    ports:
      - 3000:3000

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
